apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428
    isDefault: true
    jsonData:
      timeInterval: 5s

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      tracesToMetrics:
        datasourceUid: VictoriaMetrics
        tags: [{ key: 'service.name', value: 'service' }]
        queries:
          - name: 'Throughput'
            query: 'sum(rate(chat_system_messages_total{service=~"$__tags"}[1m]))'
      tracesToProfiles:
        datasourceUid: Pyroscope
        tags: [{ key: 'service.name', value: 'service' }]

  - name: Pyroscope
    type: grafana-pyroscope-datasource
    access: proxy
    url: http://pyroscope:4040
