apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: chat-system
spec:
  type: ExternalName
  externalName: host.docker.internal
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: chat-system
spec:
  type: ExternalName
  externalName: host.docker.internal
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: chat-system
spec:
  type: ExternalName
  externalName: host.docker.internal
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: chat-system
spec:
  type: ExternalName
  externalName: host.docker.internal

