apiVersion: v1
kind: ConfigMap
metadata:
  name: chat-config
  namespace: chat-system
data:
  # Cấu hình kết nối Hạ tầng
  NATS_URL: "nats://nats.chat-system.svc.cluster.local:4222"
  REDIS_ADDR: "redis.chat-system.svc.cluster.local:6379"
  REDIS_DB: "0"

  # Cấu hình NATS Subjects
  NATS_INBOUND_SUBJECT: "inbound.messages"
  NATS_INBOUND_STREAM: "CHAT_INBOUND"
  NATS_INBOUND_CONSUMER_GROUP: "chat_workers"
  NATS_OUTBOUND_SUBJECT_PREFIX: "gateway.outbound"

  # Cấu hình Ports & Delivery Mode
  WS_PORT: "8080"
  GRPC_PORT: "50051"
  DELIVERY_MODE: "grpc" # "grpc" or "broker"
  PRESENCE_TTL: "60"
---
apiVersion: v1
kind: Secret
metadata:
  name: chat-secrets
  namespace: chat-system
type: Opaque
data:
  # Base64 of secret key / password (eg. secret "my-jwt-secret")
  # You can create by: echo -n 'my-jwt-secret' | base64
  JWT_ACCESS_TOKEN_SECRET: bXktand0LXNlY3JldA==
  REDIS_PASSWORD: ""
