// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: pkg/proto/ws_gateway.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PushMessageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ClientMsgId    string                 `protobuf:"bytes,2,opt,name=client_msg_id,json=clientMsgId,proto3" json:"client_msg_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,3,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	SenderId       string                 `protobuf:"bytes,4,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	ReceiverId     string                 `protobuf:"bytes,5,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	Content        string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`
	Type           string                 `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	Timestamp      int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Payload        []byte                 `protobuf:"bytes,9,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PushMessageRequest) Reset() {
	*x = PushMessageRequest{}
	mi := &file_pkg_proto_ws_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMessageRequest) ProtoMessage() {}

func (x *PushMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ws_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMessageRequest.ProtoReflect.Descriptor instead.
func (*PushMessageRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ws_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *PushMessageRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *PushMessageRequest) GetClientMsgId() string {
	if x != nil {
		return x.ClientMsgId
	}
	return ""
}

func (x *PushMessageRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *PushMessageRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *PushMessageRequest) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *PushMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PushMessageRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PushMessageRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PushMessageRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type PushMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushMessageResponse) Reset() {
	*x = PushMessageResponse{}
	mi := &file_pkg_proto_ws_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMessageResponse) ProtoMessage() {}

func (x *PushMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_ws_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMessageResponse.ProtoReflect.Descriptor instead.
func (*PushMessageResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_ws_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *PushMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PushMessageResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_pkg_proto_ws_gateway_proto protoreflect.FileDescriptor

const file_pkg_proto_ws_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1apkg/proto/ws_gateway.proto\x12\agateway\"\xa4\x02\n" +
	"\x12PushMessageRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\"\n" +
	"\rclient_msg_id\x18\x02 \x01(\tR\vclientMsgId\x12'\n" +
	"\x0fconversation_id\x18\x03 \x01(\tR\x0econversationId\x12\x1b\n" +
	"\tsender_id\x18\x04 \x01(\tR\bsenderId\x12\x1f\n" +
	"\vreceiver_id\x18\x05 \x01(\tR\n" +
	"receiverId\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\x12\x18\n" +
	"\apayload\x18\t \x01(\fR\apayload\"T\n" +
	"\x13PushMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage2b\n" +
	"\x10WSGatewayService\x12N\n" +
	"\x11PushMessageToUser\x12\x1b.gateway.PushMessageRequest\x1a\x1c.gateway.PushMessageResponseB\x1dZ\x1bchat-system/pkg/proto/pb;pbb\x06proto3"

var (
	file_pkg_proto_ws_gateway_proto_rawDescOnce sync.Once
	file_pkg_proto_ws_gateway_proto_rawDescData []byte
)

func file_pkg_proto_ws_gateway_proto_rawDescGZIP() []byte {
	file_pkg_proto_ws_gateway_proto_rawDescOnce.Do(func() {
		file_pkg_proto_ws_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_ws_gateway_proto_rawDesc), len(file_pkg_proto_ws_gateway_proto_rawDesc)))
	})
	return file_pkg_proto_ws_gateway_proto_rawDescData
}

var file_pkg_proto_ws_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_ws_gateway_proto_goTypes = []any{
	(*PushMessageRequest)(nil),  // 0: gateway.PushMessageRequest
	(*PushMessageResponse)(nil), // 1: gateway.PushMessageResponse
}
var file_pkg_proto_ws_gateway_proto_depIdxs = []int32{
	0, // 0: gateway.WSGatewayService.PushMessageToUser:input_type -> gateway.PushMessageRequest
	1, // 1: gateway.WSGatewayService.PushMessageToUser:output_type -> gateway.PushMessageResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_ws_gateway_proto_init() }
func file_pkg_proto_ws_gateway_proto_init() {
	if File_pkg_proto_ws_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_ws_gateway_proto_rawDesc), len(file_pkg_proto_ws_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_ws_gateway_proto_goTypes,
		DependencyIndexes: file_pkg_proto_ws_gateway_proto_depIdxs,
		MessageInfos:      file_pkg_proto_ws_gateway_proto_msgTypes,
	}.Build()
	File_pkg_proto_ws_gateway_proto = out.File
	file_pkg_proto_ws_gateway_proto_goTypes = nil
	file_pkg_proto_ws_gateway_proto_depIdxs = nil
}
