// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: pkg/proto/ws_gateway.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WSGatewayService_PushMessageToUser_FullMethodName = "/gateway.WSGatewayService/PushMessageToUser"
)

// WSGatewayServiceClient is the client API for WSGatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WSGatewayServiceClient interface {
	PushMessageToUser(ctx context.Context, in *PushMessageRequest, opts ...grpc.CallOption) (*PushMessageResponse, error)
}

type wSGatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWSGatewayServiceClient(cc grpc.ClientConnInterface) WSGatewayServiceClient {
	return &wSGatewayServiceClient{cc}
}

func (c *wSGatewayServiceClient) PushMessageToUser(ctx context.Context, in *PushMessageRequest, opts ...grpc.CallOption) (*PushMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PushMessageResponse)
	err := c.cc.Invoke(ctx, WSGatewayService_PushMessageToUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WSGatewayServiceServer is the server API for WSGatewayService service.
// All implementations must embed UnimplementedWSGatewayServiceServer
// for forward compatibility.
type WSGatewayServiceServer interface {
	PushMessageToUser(context.Context, *PushMessageRequest) (*PushMessageResponse, error)
	mustEmbedUnimplementedWSGatewayServiceServer()
}

// UnimplementedWSGatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWSGatewayServiceServer struct{}

func (UnimplementedWSGatewayServiceServer) PushMessageToUser(context.Context, *PushMessageRequest) (*PushMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PushMessageToUser not implemented")
}
func (UnimplementedWSGatewayServiceServer) mustEmbedUnimplementedWSGatewayServiceServer() {}
func (UnimplementedWSGatewayServiceServer) testEmbeddedByValue()                          {}

// UnsafeWSGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WSGatewayServiceServer will
// result in compilation errors.
type UnsafeWSGatewayServiceServer interface {
	mustEmbedUnimplementedWSGatewayServiceServer()
}

func RegisterWSGatewayServiceServer(s grpc.ServiceRegistrar, srv WSGatewayServiceServer) {
	// If the following call panics, it indicates UnimplementedWSGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WSGatewayService_ServiceDesc, srv)
}

func _WSGatewayService_PushMessageToUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WSGatewayServiceServer).PushMessageToUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WSGatewayService_PushMessageToUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WSGatewayServiceServer).PushMessageToUser(ctx, req.(*PushMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WSGatewayService_ServiceDesc is the grpc.ServiceDesc for WSGatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WSGatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gateway.WSGatewayService",
	HandlerType: (*WSGatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushMessageToUser",
			Handler:    _WSGatewayService_PushMessageToUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/ws_gateway.proto",
}
